#!/bin/bash
PUID=${PUID:-911}
PGID=${PGID:-911}
groupmod -o -g "$PGID" abc
usermod -o -u "$PUID" abc
echo "
User uid:    $(id -u abc)
User gid:    $(id -g abc)
-------------------------------------
"
chown -R abc:abc /app
chown -R abc:abc /config
su -s /bin/sh -c "mono /app/eco/EcoServer.exe -nogui" abc
